spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: task-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  flyway:
    enabled: false
    baseline-on-migrate: true

server:
  port: 8082

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.kafka.core: DEBUG
    org.springframework.kafka.producer: DEBUG
    org.apache.kafka.clients.producer: DEBUG
    org.apache.kafka.common: INFO
    org.apache.kafka: INFO
    org.apache.kafka.clients: INFO
    org.apache.kafka.clients.consumer: OFF
    org.springframework.kafka.listener: OFF
    com.butorin.taskservice.service.KafkaConsumerService: OFF